import pandas as pd
import requests
import json
from typing import List, Dict, Optional

class StockSuggestions:
    """Provide stock symbol suggestions for North American markets"""
    
    def __init__(self):
        # Popular Canadian stocks (TSX)
        self.canadian_stocks = {
            'SHOP.TO': 'Shopify Inc.',
            'RY.TO': 'Royal Bank of Canada',
            'TD.TO': 'Toronto-Dominion Bank',
            'CNR.TO': 'Canadian National Railway',
            'BNS.TO': 'Bank of Nova Scotia',
            'BMO.TO': 'Bank of Montreal',
            'CNQ.TO': 'Canadian Natural Resources',
            'CP.TO': 'Canadian Pacific Railway',
            'SU.TO': 'Suncor Energy Inc.',
            'ENB.TO': 'Enbridge Inc.',
            'TRI.TO': 'Thomson Reuters Corporation',
            'WCN.TO': 'Waste Connections Inc.',
            'CSU.TO': 'Constellation Software Inc.',
            'ATD.TO': 'Alimentation Couche-Tard Inc.',
            'MFC.TO': 'Manulife Financial Corporation',
            'SLF.TO': 'Sun Life Financial Inc.',
            'CCL-B.TO': 'CCL Industries Inc.',
            'QSR.TO': 'Restaurant Brands International',
            'DOL.TO': 'Dollarama Inc.',
            'WFG.TO': 'West Fraser Timber Co.',
            'TIH.TO': 'Toromont Industries Ltd.',
            'FFH.TO': 'Fairfax Financial Holdings',
            'GIB-A.TO': 'CGI Inc.',
            'KL.TO': 'Kirkland Lake Gold Ltd.',
            'AEM.TO': 'Agnico Eagle Mines Limited',
            'WPM.TO': 'Wheaton Precious Metals',
            'NTR.TO': 'Nutrien Ltd.',
            'CNI.TO': 'Canadian National Railway',
            'TRP.TO': 'TC Energy Corporation',
            'PPL.TO': 'Pembina Pipeline Corporation',
            'KEY.TO': 'Keyera Corp.',
            'PXT.TO': 'Parex Resources Inc.',
            'ARX.TO': 'ARC Resources Ltd.',
            'CVE.TO': 'Cenovus Energy Inc.',
            'IMO.TO': 'Imperial Oil Limited',
            'HSE.TO': 'Husky Energy Inc.',
            'WCP.TO': 'Whitecap Resources Inc.',
            'FNV.TO': 'Franco-Nevada Corporation',
            'ABX.TO': 'Barrick Gold Corporation',
            'K.TO': 'Kinross Gold Corporation',
            'CG.TO': 'Centerra Gold Inc.',
            'ELD.TO': 'Eldorado Gold Corporation',
            'IAG.TO': 'IAMGOLD Corporation',
            'NGT.TO': 'Newmont Corporation',
            'SVM.TO': 'Silvercorp Metals Inc.',
            'PAAS.TO': 'Pan American Silver Corp.',
            'FS.TO': 'Fortuna Silver Mines Inc.',
            'MAG.TO': 'MAG Silver Corp.',
            'FVI.TO': 'Fortuna Silver Mines Inc.',
        }
        
        # Popular US stocks
        self.us_stocks = {
            'AAPL': 'Apple Inc.',
            'MSFT': 'Microsoft Corporation',
            'GOOGL': 'Alphabet Inc.',
            'AMZN': 'Amazon.com Inc.',
            'TSLA': 'Tesla Inc.',
            'NVDA': 'NVIDIA Corporation',
            'META': 'Meta Platforms Inc.',
            'NFLX': 'Netflix Inc.',
            'AMD': 'Advanced Micro Devices',
            'INTC': 'Intel Corporation',
            'PYPL': 'PayPal Holdings Inc.',
            'ADBE': 'Adobe Inc.',
            'CRM': 'Salesforce Inc.',
            'ORCL': 'Oracle Corporation',
            'IBM': 'International Business Machines',
            'UBER': 'Uber Technologies Inc.',
            'SPOT': 'Spotify Technology S.A.',
            'TWTR': 'Twitter Inc.',
            'SNAP': 'Snap Inc.',
            'ZOOM': 'Zoom Video Communications',
            'DOCU': 'DocuSign Inc.',
            'SQ': 'Block Inc.',
            'ROKU': 'Roku Inc.',
            'PINS': 'Pinterest Inc.',
            'DDOG': 'Datadog Inc.',
            'SNOW': 'Snowflake Inc.',
            'PLTR': 'Palantir Technologies Inc.',
            'RBLX': 'Roblox Corporation',
            'COIN': 'Coinbase Global Inc.',
            'HOOD': 'Robinhood Markets Inc.',
            'RIVN': 'Rivian Automotive Inc.',
            'LCID': 'Lucid Group Inc.',
            'NIO': 'NIO Inc.',
            'XPEV': 'XPeng Inc.',
            'LI': 'Li Auto Inc.',
            'BABA': 'Alibaba Group Holding',
            'JD': 'JD.com Inc.',
            'PDD': 'PDD Holdings Inc.',
            'BIDU': 'Baidu Inc.',
            'NTES': 'NetEase Inc.',
            'TME': 'Tencent Music Entertainment',
            'V': 'Visa Inc.',
            'MA': 'Mastercard Incorporated',
            'JPM': 'JPMorgan Chase & Co.',
            'BAC': 'Bank of America Corporation',
            'WFC': 'Wells Fargo & Company',
            'GS': 'Goldman Sachs Group Inc.',
            'MS': 'Morgan Stanley',
            'C': 'Citigroup Inc.',
            'AXP': 'American Express Company',
            'KO': 'Coca-Cola Company',
            'PEP': 'PepsiCo Inc.',
            'MCD': 'McDonald\'s Corporation',
            'SBUX': 'Starbucks Corporation',
            'DIS': 'Walt Disney Company',
            'NKE': 'Nike Inc.',
            'HD': 'Home Depot Inc.',
            'LOW': 'Lowe\'s Companies Inc.',
            'TGT': 'Target Corporation',
            'WMT': 'Walmart Inc.',
            'COST': 'Costco Wholesale Corporation',
            'AMGN': 'Amgen Inc.',
            'GILD': 'Gilead Sciences Inc.',
            'MRNA': 'Moderna Inc.',
            'PFE': 'Pfizer Inc.',
            'JNJ': 'Johnson & Johnson',
            'UNH': 'UnitedHealth Group Inc.',
            'CVS': 'CVS Health Corporation',
            'ABBV': 'AbbVie Inc.',
            'LLY': 'Eli Lilly and Company',
            'BMY': 'Bristol-Myers Squibb',
            'MRK': 'Merck & Co. Inc.',
            'BIIB': 'Biogen Inc.',
            'REGN': 'Regeneron Pharmaceuticals',
            'VRTX': 'Vertex Pharmaceuticals',
            'XOM': 'Exxon Mobil Corporation',
            'CVX': 'Chevron Corporation',
            'COP': 'ConocoPhillips',
            'OXY': 'Occidental Petroleum',
            'SLB': 'Schlumberger Limited',
            'HAL': 'Halliburton Company',
            'DVN': 'Devon Energy Corporation',
            'EOG': 'EOG Resources Inc.',
            'PXD': 'Pioneer Natural Resources',
            'MPC': 'Marathon Petroleum Corporation',
            'VLO': 'Valero Energy Corporation',
            'PSX': 'Phillips 66',
            'SPY': 'SPDR S&P 500 ETF Trust',
            'QQQ': 'Invesco QQQ Trust',
            'IWM': 'iShares Russell 2000 ETF',
            'VTI': 'Vanguard Total Stock Market ETF',
            'VOO': 'Vanguard S&P 500 ETF',
            'VEA': 'Vanguard FTSE Developed Markets ETF',
            'VWO': 'Vanguard FTSE Emerging Markets ETF',
            'AGG': 'iShares Core U.S. Aggregate Bond ETF',
            'BND': 'Vanguard Total Bond Market ETF',
            'GLD': 'SPDR Gold Shares',
            'SLV': 'iShares Silver Trust',
            'USO': 'United States Oil Fund',
            'UNG': 'United States Natural Gas Fund',
            'TLT': 'iShares 20+ Year Treasury Bond ETF',
            'HYG': 'iShares iBoxx High Yield Corporate Bond ETF',
            'LQD': 'iShares iBoxx Investment Grade Corporate Bond ETF',
            'EFA': 'iShares MSCI EAFE ETF',
            'EEM': 'iShares MSCI Emerging Markets ETF',
            'RSP': 'Invesco S&P 500 Equal Weight ETF',
            'DIA': 'SPDR Dow Jones Industrial Average ETF',
            'MDY': 'SPDR S&P MidCap 400 ETF',
            'SLY': 'SPDR S&P 600 Small Cap ETF',
            'XLE': 'Energy Select Sector SPDR Fund',
            'XLF': 'Financial Select Sector SPDR Fund',
            'XLK': 'Technology Select Sector SPDR Fund',
            'XLI': 'Industrial Select Sector SPDR Fund',
            'XLV': 'Health Care Select Sector SPDR Fund',
            'XLY': 'Consumer Discretionary Select Sector SPDR Fund',
            'XLP': 'Consumer Staples Select Sector SPDR Fund',
            'XLU': 'Utilities Select Sector SPDR Fund',
            'XLRE': 'Real Estate Select Sector SPDR Fund',
            'XLB': 'Materials Select Sector SPDR Fund',
            'XME': 'SPDR S&P Metals and Mining ETF',
            'GDX': 'VanEck Vectors Gold Miners ETF',
            'GDXJ': 'VanEck Vectors Junior Gold Miners ETF',
            'SIL': 'Global X Silver Miners ETF',
            'COPX': 'Global X Copper Miners ETF',
            'ICLN': 'iShares Global Clean Energy ETF',
            'PBW': 'Invesco WilderHill Clean Energy ETF',
            'ARKK': 'ARK Innovation ETF',
            'ARKQ': 'ARK Autonomous Technology & Robotics ETF',
            'ARKW': 'ARK Next Generation Internet ETF',
            'ARKG': 'ARK Genomics Revolution ETF',
            'ARKF': 'ARK Fintech Innovation ETF',
        }
        
        # TSX-V stocks (smaller Canadian companies)
        self.tsx_v_stocks = {
            'FIRE.V': 'Supreme Cannabis Company',
            'WEED.V': 'Canopy Growth Corporation',
            'ACB.V': 'Aurora Cannabis Inc.',
            'CRON.V': 'Cronos Group Inc.',
            'TLRY.V': 'Tilray Inc.',
            'HEXO.V': 'HEXO Corp.',
            'OGI.V': 'Organigram Holdings Inc.',
            'LABS.V': 'MediPharm Labs Corp.',
            'VIDA.V': 'Vida Cannabis Corp.',
            'TGOD.V': 'The Green Organic Dutchman',
            'ZENA.V': 'Zenabis Global Inc.',
            'CLIQ.V': 'Cliq Digital AG',
            'NUMI.V': 'Numinus Wellness Inc.',
            'MMED.V': 'Mind Medicine Inc.',
            'CYBN.V': 'Cybin Inc.',
            'FTRP.V': 'Field Trip Health Ltd.',
            'SHRM.V': 'Champignon Brands Inc.',
            'BUZZ.V': 'BuzzFeed Inc.',
            'GDNP.V': 'GreenSpace Brands Inc.',
            'BEER.V': 'Benchmark Brewing Company',
            'NTAR.V': 'Nextech AR Solutions Corp.',
            'NETE.V': 'Network Media Group Inc.',
            'DGTL.V': 'Digital Brands Group Corp.',
            'HIRE.V': 'Hire Technologies Inc.',
            'NRTH.V': 'Northern Graphite Corporation',
            'FLUX.V': 'Flux Power Holdings Inc.',
            'SOLR.V': 'Solarvest BioEnergy Inc.',
            'GRVI.V': 'Grove Inc.',
            'GAIA.V': 'Gaia Grow Corp.',
            'SOIL.V': 'Soil Connect Inc.',
            'TECH.V': 'Technosign Inc.',
            'LAKE.V': 'Lake Resources N.L.',
            'ROCK.V': 'Rock Tech Lithium Inc.',
            'FTCO.V': 'Fortune Bay Corp.',
            'GOLD.V': 'Gold Reserve Inc.',
            'SILV.V': 'SilverCrest Metals Inc.',
            'ZINC.V': 'Zinc8 Energy Solutions Inc.',
            'LION.V': 'Lion One Metals Limited',
            'GPRO.V': 'GoPro Inc.',
            'GDXJ.V': 'Junior Gold Miners ETF',
            'RECO.V': 'Reconnaissance Energy Africa',
            'CSTR.V': 'CanStrip Resources Corp.',
            'MOGO.V': 'Mogo Inc.',
            'BIGG.V': 'BIGG Digital Assets Inc.',
            'HIVE.V': 'HIVE Blockchain Technologies',
            'BITF.V': 'Bitfarms Ltd.',
            'DMGI.V': 'DMG Blockchain Solutions Inc.',
            'FORT.V': 'Fortress Technologies Inc.',
            'COIN.V': 'Coinbase Global Inc.',
            'GLXY.V': 'Galaxy Digital Holdings Ltd.',
            'BTCC.V': 'Purpose Bitcoin ETF',
            'ETHX.V': 'CI Galaxy Ethereum ETF',
            'BTCX.V': 'CI Galaxy Bitcoin ETF',
            'EBIT.V': 'Evolve Bitcoin ETF',
            'BTCY.V': 'Fidelity Advantage Bitcoin ETF',
            'QBTC.V': 'Purpose Bitcoin ETF',
            'ETHQ.V': 'Purpose Ether ETF',
            'BTCQ.V': 'Purpose Bitcoin ETF',
            'MSTR.V': 'MicroStrategy Incorporated',
            'RIOT.V': 'Riot Blockchain Inc.',
            'MARA.V': 'Marathon Digital Holdings',
            'CLSK.V': 'CleanSpark Inc.',
            'BTBT.V': 'Bit Digital Inc.',
            'EBON.V': 'Ebang International Holdings',
            'CAN.V': 'Canaan Inc.',
            'BTCM.V': 'BTC Digital Ltd.',
            'WULF.V': 'TeraWulf Inc.',
            'GREE.V': 'Greenidge Generation Holdings',
            'CIFR.V': 'Cipher Mining Inc.',
            'BFRI.V': 'Bitfufu Inc.',
            'CORZ.V': 'Core Scientific Inc.',
            'APLD.V': 'Applied Digital Corporation',
            'ARBK.V': 'Argo Blockchain PLC',
            'HUTMF.V': 'Hut 8 Mining Corp.',
            'BITK.V': 'Bitfarms Ltd.',
            'CCTL.V': 'CatalystOne Solutions ASA',
            'MIGI.V': 'Mogo Inc.',
            'VERY.V': 'Vicinity Motor Corp.',
            'DGHI.V': 'Digihost Technology Inc.',
            'INTV.V': 'Integral Technologies Inc.',
            'NVEI.V': 'Nuvei Corporation',
            'LSPD.V': 'Lightspeed POS Inc.',
            'REAL.V': 'Real Matters Inc.',
            'DOCN.V': 'DigitalOcean Holdings Inc.',
            'DOCU.V': 'DocuSign Inc.',
            'ZM.V': 'Zoom Video Communications',
            'TEAM.V': 'Atlassian Corporation',
            'NOW.V': 'ServiceNow Inc.',
            'WDAY.V': 'Workday Inc.',
            'OKTA.V': 'Okta Inc.',
            'SNOW.V': 'Snowflake Inc.',
            'DDOG.V': 'Datadog Inc.',
            'ESTC.V': 'Elastic N.V.',
            'SPLK.V': 'Splunk Inc.',
            'CRWD.V': 'CrowdStrike Holdings Inc.',
            'ZS.V': 'Zscaler Inc.',
            'PANW.V': 'Palo Alto Networks Inc.',
            'FTNT.V': 'Fortinet Inc.',
            'CYBR.V': 'CyberArk Software Ltd.',
            'TENB.V': 'Tenable Holdings Inc.',
            'SAIL.V': 'SailPoint Technologies Holdings',
            'VRNS.V': 'Varonis Systems Inc.',
            'PFPT.V': 'Proofpoint Inc.',
            'FEYE.V': 'FireEye Inc.',
            'CHKP.V': 'Check Point Software Technologies',
            'S.V': 'SentinelOne Inc.',
            'QLYS.V': 'Qualys Inc.',
            'RPRX.V': 'Rapid7 Inc.',
            'AVGO.V': 'Broadcom Inc.',
            'QCOM.V': 'Qualcomm Incorporated',
            'TXN.V': 'Texas Instruments Incorporated',
            'AVGO.V': 'Broadcom Inc.',
            'LRCX.V': 'Lam Research Corporation',
            'AMAT.V': 'Applied Materials Inc.',
            'KLAC.V': 'KLA Corporation',
            'MCHP.V': 'Microchip Technology Incorporated',
            'MXIM.V': 'Maxim Integrated Products Inc.',
            'SWKS.V': 'Skyworks Solutions Inc.',
            'QRVO.V': 'Qorvo Inc.',
            'MPWR.V': 'Monolithic Power Systems Inc.',
            'SLAB.V': 'Silicon Laboratories Inc.',
            'CRUS.V': 'Cirrus Logic Inc.',
            'RMBS.V': 'Rambus Inc.',
            'MRVL.V': 'Marvell Technology Inc.',
            'XLNX.V': 'Xilinx Inc.',
            'ALTR.V': 'Altair Engineering Inc.',
            'CDNS.V': 'Cadence Design Systems Inc.',
            'SNPS.V': 'Synopsys Inc.',
            'ANSS.V': 'ANSYS Inc.',
            'ADSK.V': 'Autodesk Inc.',
            'PTC.V': 'PTC Inc.',
            'WORK.V': 'Slack Technologies Inc.',
            'FIVN.V': 'Five9 Inc.',
            'RING.V': 'Ring Inc.',
            'TWLO.V': 'Twilio Inc.',
            'BAND.V': 'Bandwidth Inc.',
            'SMAR.V': 'Smartsheet Inc.',
            'PLAN.V': 'Anaplan Inc.',
            'PCTY.V': 'Paylocity Holding Corporation',
            'PAYC.V': 'Paycom Software Inc.',
            'COUP.V': 'Coupa Software Incorporated',
            'BILL.V': 'Bill.com Holdings Inc.',
            'AFRM.V': 'Affirm Holdings Inc.',
            'UPST.V': 'Upstart Holdings Inc.',
            'OPEN.V': 'Opendoor Technologies Inc.',
            'RDFN.V': 'Redfin Corporation',
            'Z.V': 'Zillow Group Inc.',
            'EXPI.V': 'eXp World Holdings Inc.',
            'COMP.V': 'Compass Inc.',
            'RMAX.V': 'RE/MAX Holdings Inc.',
            'HOUS.V': 'Anywhere Real Estate Inc.',
            'RESI.V': 'Front Yard Residential Corporation',
            'AMC.V': 'AMC Entertainment Holdings Inc.',
            'NKLA.V': 'Nikola Corporation',
            'WKHS.V': 'Workhorse Group Inc.',
            'RIDE.V': 'Lordstown Motors Corp.',
            'GOEV.V': 'Canoo Inc.',
            'HYLN.V': 'Hyliion Holdings Corp.',
            'BLNK.V': 'Blink Charging Co.',
            'CHPT.V': 'ChargePoint Holdings Inc.',
            'EVGO.V': 'EVgo Inc.',
            'VLTA.V': 'Volta Inc.',
            'SBE.V': 'Solid Power Inc.',
            'QS.V': 'QuantumScape Corporation',
            'STEM.V': 'Stem Inc.',
            'ENPH.V': 'Enphase Energy Inc.',
            'SEDG.V': 'SolarEdge Technologies Inc.',
            'SPWR.V': 'SunPower Corporation',
            'FSLR.V': 'First Solar Inc.',
            'RUN.V': 'Sunrun Inc.',
            'NOVA.V': 'Sunnova Energy International',
            'CSIQ.V': 'Canadian Solar Inc.',
            'JKS.V': 'JinkoSolar Holding Co. Ltd.',
            'DQ.V': 'Daqo New Energy Corp.',
            'SOL.V': 'Emeren Group Ltd.',
            'MAXN.V': 'Maxeon Solar Technologies Ltd.',
            'ARRY.V': 'Array Technologies Inc.',
            'BEPC.V': 'Brookfield Renewable Corporation',
            'NEE.V': 'NextEra Energy Inc.',
            'AEP.V': 'American Electric Power Company',
            'SO.V': 'Southern Company',
            'D.V': 'Dominion Energy Inc.',
            'DUK.V': 'Duke Energy Corporation',
            'EXC.V': 'Exelon Corporation',
            'XEL.V': 'Xcel Energy Inc.',
            'WEC.V': 'WEC Energy Group Inc.',
            'ED.V': 'Consolidated Edison Inc.',
            'EIX.V': 'Edison International',
            'SRE.V': 'Sempra Energy',
            'PEG.V': 'Public Service Enterprise Group',
            'PCG.V': 'PG&E Corporation',
            'AWK.V': 'American Water Works Company',
            'ATO.V': 'Atmos Energy Corporation',
            'CMS.V': 'CMS Energy Corporation',
            'DTE.V': 'DTE Energy Company',
            'NI.V': 'NiSource Inc.',
            'LNT.V': 'Alliant Energy Corporation',
            'EVRG.V': 'Evergy Inc.',
            'ES.V': 'Eversource Energy',
            'FE.V': 'FirstEnergy Corp.',
            'CNP.V': 'CenterPoint Energy Inc.',
            'ETR.V': 'Entergy Corporation',
            'AES.V': 'AES Corporation',
            'PPL.V': 'PPL Corporation',
            'PNW.V': 'Pinnacle West Capital Corporation',
            'UGI.V': 'UGI Corporation',
            'SWX.V': 'Southwest Gas Holdings Inc.',
            'OGE.V': 'OGE Energy Corp.',
            'MDU.V': 'MDU Resources Group Inc.',
            'BKH.V': 'Black Hills Corporation',
            'AVA.V': 'Avista Corporation',
            'POR.V': 'Portland General Electric Company',
            'IDA.V': 'IDACORP Inc.',
            'NWE.V': 'NorthWestern Corporation',
            'OTTR.V': 'Otter Tail Corporation',
            'ALE.V': 'Allete Inc.',
            'HE.V': 'Hawaiian Electric Industries',
            'UTL.V': 'Unitil Corporation',
            'MGEE.V': 'MGE Energy Inc.',
            'WR.V': 'Weir Group PLC',
            'SPXC.V': 'SPX Technologies Inc.',
            'FLS.V': 'Flowserve Corporation',
            'PH.V': 'Parker-Hannifin Corporation',
            'ETN.V': 'Eaton Corporation PLC',
            'EMR.V': 'Emerson Electric Co.',
            'ROK.V': 'Rockwell Automation Inc.',
            'HON.V': 'Honeywell International Inc.',
            'ITW.V': 'Illinois Tool Works Inc.',
            'TXT.V': 'Textron Inc.',
            'RTX.V': 'Raytheon Technologies Corporation',
            'LMT.V': 'Lockheed Martin Corporation',
            'NOC.V': 'Northrop Grumman Corporation',
            'GD.V': 'General Dynamics Corporation',
            'BA.V': 'Boeing Company',
            'HII.V': 'Huntington Ingalls Industries',
            'LHX.V': 'L3Harris Technologies Inc.',
            'TDG.V': 'TransDigm Group Incorporated',
            'CW.V': 'Curtiss-Wright Corporation',
            'KTOS.V': 'Kratos Defense & Security Solutions',
            'AVAV.V': 'AeroVironment Inc.',
            'AJRD.V': 'Aerojet Rocketdyne Holdings Inc.',
            'MRCY.V': 'Mercury Systems Inc.',
            'VSAT.V': 'Viasat Inc.',
            'GILT.V': 'Gilat Satellite Networks Ltd.',
            'IRDM.V': 'Iridium Communications Inc.',
            'GSAT.V': 'Globalstar Inc.',
            'ORBC.V': 'Orbcomm Inc.',
            'MAXR.V': 'Maxar Technologies Inc.',
            'SPCE.V': 'Virgin Galactic Holdings Inc.',
            'RKLB.V': 'Rocket Lab USA Inc.',
            'ASTR.V': 'Astra Space Inc.',
            'VACQ.V': 'Vector Acquisition Corporation',
            'BKSY.V': 'BlackSky Technology Inc.',
            'PLNT.V': 'Planet Labs PBC',
            'SPIR.V': 'Spire Global Inc.',
            'ASTS.V': 'AST SpaceMobile Inc.',
            'MNTS.V': 'Momentus Inc.',
            'SRAC.V': 'Stable Road Acquisition Corp.',
            'NGCA.V': 'NextGen Acquisition Corporation',
            'IMPX.V': 'AEA-Bridges Impact Corp.',
            'TPGY.V': 'TPG Pace Beneficial Finance Corp.',
            'FGNA.V': 'FG New America Acquisition Corp.',
            'DFNS.V': 'Gores Metropoulos II Inc.',
            'GXGX.V': 'GX Acquisition Corp. II',
            'HCCO.V': 'HCM Acquisition Corp.',
            'TWND.V': 'Tailwind Acquisition Corp.',
            'ACTC.V': 'ArcLight Clean Transition Corp.',
            'PDAC.V': 'Peridot Acquisition Corp.',
            'ZNTE.V': 'Zanite Acquisition Corp.',
            'CLOV.V': 'Clover Health Investments Corp.',
            'SOFI.V': 'SoFi Technologies Inc.',
            'PTRA.V': 'Proterra Inc.',
            'JOBY.V': 'Joby Aviation Inc.',
            'LILM.V': 'Lilium N.V.',
            'EVTL.V': 'Vertical Aerospace Ltd.',
            'ACHR.V': 'Archer Aviation Inc.',
            'BLDE.V': 'Blade Air Mobility Inc.',
            'ESPR.V': 'Esperion Therapeutics Inc.',
            'VRTX.V': 'Vertex Pharmaceuticals Incorporated',
            'BIIB.V': 'Biogen Inc.',
            'REGN.V': 'Regeneron Pharmaceuticals Inc.',
            'AMGN.V': 'Amgen Inc.',
            'BMRN.V': 'BioMarin Pharmaceutical Inc.',
            'ILMN.V': 'Illumina Inc.',
            'INCY.V': 'Incyte Corporation',
            'ACAD.V': 'ACADIA Pharmaceuticals Inc.',
            'HALO.V': 'Halozyme Therapeutics Inc.',
            'EXEL.V': 'Exelixis Inc.',
            'FOLD.V': 'Amicus Therapeutics Inc.',
            'IONS.V': 'Ionis Pharmaceuticals Inc.',
            'SAGE.V': 'Sage Therapeutics Inc.',
            'RARE.V': 'Ultragenyx Pharmaceutical Inc.',
            'BLUE.V': 'bluebird bio Inc.',
            'CRSP.V': 'CRISPR Therapeutics AG',
            'EDIT.V': 'Editas Medicine Inc.',
            'NTLA.V': 'Intellia Therapeutics Inc.',
            'BEAM.V': 'Beam Therapeutics Inc.',
            'PRIME.V': 'Prime Medicine Inc.',
            'VERV.V': 'Verve Therapeutics Inc.',
            'MASS.V': 'Massimo Squalantotinib Inc.',
            'ALNY.V': 'Alnylam Pharmaceuticals Inc.',
            'ARWR.V': 'Arrowhead Pharmaceuticals Inc.',
            'DRNA.V': 'Dicerna Pharmaceuticals Inc.',
            'MORF.V': 'Morphic Holding Inc.',
            'TGTX.V': 'TG Therapeutics Inc.',
            'ADPT.V': 'Adaptive Biotechnologies Corporation',
            'FATE.V': 'Fate Therapeutics Inc.',
            'KITE.V': 'Kite Pharma Inc.',
            'JUNO.V': 'Juno Therapeutics Inc.',
            'CELG.V': 'Celgene Corporation',
            'NKTR.V': 'Nektar Therapeutics',
            'BPMC.V': 'Blueprint Medicines Corporation',
            'PTCT.V': 'PTC Therapeutics Inc.',
            'SGEN.V': 'Seagen Inc.',
            'IMMU.V': 'Immunomedics Inc.',
            'AXSM.V': 'Axsome Therapeutics Inc.',
            'CRBP.V': 'Corbus Pharmaceuticals Holdings',
            'CBPO.V': 'Canopy Growth Corporation',
            'WEED.V': 'Canopy Growth Corporation',
            'APHA.V': 'Aphria Inc.',
            'CRON.V': 'Cronos Group Inc.',
            'TLRY.V': 'Tilray Inc.',
            'CGC.V': 'Canopy Growth Corporation',
            'HEXO.V': 'HEXO Corp.',
            'OGI.V': 'OrganiGram Holdings Inc.',
            'LABS.V': 'MediPharm Labs Corp.',
            'VIDA.V': 'Vida Cannabis Corp.',
            'TGOD.V': 'The Green Organic Dutchman Holdings Ltd.',
            'ZENA.V': 'Zenabis Global Inc.',
            'CLIQ.V': 'Cliq Digital AG',
            'NUMI.V': 'Numinus Wellness Inc.',
            'MMED.V': 'Mind Medicine (MindMed) Inc.',
            'CYBN.V': 'Cybin Inc.',
            'FTRP.V': 'Field Trip Health Ltd.',
            'SHRM.V': 'Champignon Brands Inc.',
            'BUZZ.V': 'BuzzFeed Inc.',
            'GDNP.V': 'GreenSpace Brands Inc.',
            'BEER.V': 'Benchmark Brewing Company',
            'NTAR.V': 'Nextech AR Solutions Corp.',
            'NETE.V': 'Network Media Group Inc.',
            'DGTL.V': 'Digital Brands Group Corp.',
            'HIRE.V': 'Hire Technologies Inc.',
            'NRTH.V': 'Northern Graphite Corporation',
            'FLUX.V': 'Flux Power Holdings Inc.',
            'SOLR.V': 'Solarvest BioEnergy Inc.',
            'GRVI.V': 'Grove Inc.',
            'GAIA.V': 'Gaia Grow Corp.',
            'SOIL.V': 'Soil Connect Inc.',
            'TECH.V': 'Technosign Inc.',
            'LAKE.V': 'Lake Resources N.L.',
            'ROCK.V': 'Rock Tech Lithium Inc.',
            'FTCO.V': 'Fortune Bay Corp.',
            'GOLD.V': 'Gold Reserve Inc.',
            'SILV.V': 'SilverCrest Metals Inc.',
            'ZINC.V': 'Zinc8 Energy Solutions Inc.',
            'LION.V': 'Lion One Metals Limited',
            'GPRO.V': 'GoPro Inc.',
            'GDXJ.V': 'VanEck Vectors Junior Gold Miners ETF',
            'RECO.V': 'Reconnaissance Energy Africa Ltd.',
            'CSTR.V': 'CanStrip Resources Corp.',
            'MOGO.V': 'Mogo Inc.',
            'BIGG.V': 'BIGG Digital Assets Inc.',
            'HIVE.V': 'HIVE Blockchain Technologies Ltd.',
            'BITF.V': 'Bitfarms Ltd.',
            'DMGI.V': 'DMG Blockchain Solutions Inc.',
            'FORT.V': 'Fortress Technologies Inc.',
            'COIN.V': 'Coinbase Global Inc.',
            'GLXY.V': 'Galaxy Digital Holdings Ltd.',
            'BTCC.V': 'Purpose Bitcoin ETF',
            'ETHX.V': 'CI Galaxy Ethereum ETF',
            'BTCX.V': 'CI Galaxy Bitcoin ETF',
            'EBIT.V': 'Evolve Bitcoin ETF',
            'BTCY.V': 'Fidelity Advantage Bitcoin ETF',
            'QBTC.V': 'Purpose Bitcoin ETF',
            'ETHQ.V': 'Purpose Ether ETF',
            'BTCQ.V': 'Purpose Bitcoin ETF',
            'MSTR.V': 'MicroStrategy Incorporated',
            'RIOT.V': 'Riot Blockchain Inc.',
            'MARA.V': 'Marathon Digital Holdings Inc.',
            'CLSK.V': 'CleanSpark Inc.',
            'BTBT.V': 'Bit Digital Inc.',
            'EBON.V': 'Ebang International Holdings Inc.',
            'CAN.V': 'Canaan Inc.',
            'BTCM.V': 'BTC Digital Ltd.',
            'WULF.V': 'TeraWulf Inc.',
            'GREE.V': 'Greenidge Generation Holdings Inc.',
            'CIFR.V': 'Cipher Mining Inc.',
            'BFRI.V': 'Bitfufu Inc.',
            'CORZ.V': 'Core Scientific Inc.',
            'APLD.V': 'Applied Digital Corporation',
            'ARBK.V': 'Argo Blockchain PLC',
            'HUTMF.V': 'Hut 8 Mining Corp.',
            'BITK.V': 'Bitfarms Ltd.',
            'CCTL.V': 'CatalystOne Solutions ASA',
            'MIGI.V': 'Mogo Inc.',
            'VERY.V': 'Vicinity Motor Corp.',
            'DGHI.V': 'Digihost Technology Inc.',
            'INTV.V': 'Integral Technologies Inc.',
            'NVEI.V': 'Nuvei Corporation',
            'LSPD.V': 'Lightspeed POS Inc.',
            'REAL.V': 'Real Matters Inc.',
            'DOCN.V': 'DigitalOcean Holdings Inc.',
            'DOCU.V': 'DocuSign Inc.',
            'ZM.V': 'Zoom Video Communications Inc.',
            'TEAM.V': 'Atlassian Corporation Plc',
            'NOW.V': 'ServiceNow Inc.',
            'WDAY.V': 'Workday Inc.',
            'OKTA.V': 'Okta Inc.',
            'SNOW.V': 'Snowflake Inc.',
            'DDOG.V': 'Datadog Inc.',
            'ESTC.V': 'Elastic N.V.',
            'SPLK.V': 'Splunk Inc.',
            'CRWD.V': 'CrowdStrike Holdings Inc.',
            'ZS.V': 'Zscaler Inc.',
            'PANW.V': 'Palo Alto Networks Inc.',
            'FTNT.V': 'Fortinet Inc.',
            'CYBR.V': 'CyberArk Software Ltd.',
            'TENB.V': 'Tenable Holdings Inc.',
            'SAIL.V': 'SailPoint Technologies Holdings Inc.',
            'VRNS.V': 'Varonis Systems Inc.',
            'PFPT.V': 'Proofpoint Inc.',
            'FEYE.V': 'FireEye Inc.',
            'CHKP.V': 'Check Point Software Technologies Ltd.',
            'S.V': 'SentinelOne Inc.',
            'QLYS.V': 'Qualys Inc.',
            'RPRX.V': 'Rapid7 Inc.',
            'AVGO.V': 'Broadcom Inc.',
            'QCOM.V': 'QUALCOMM Incorporated',
            'TXN.V': 'Texas Instruments Incorporated',
            'AVGO.V': 'Broadcom Inc.',
            'LRCX.V': 'Lam Research Corporation',
            'AMAT.V': 'Applied Materials Inc.',
            'KLAC.V': 'KLA Corporation',
            'MCHP.V': 'Microchip Technology Incorporated',
            'MXIM.V': 'Maxim Integrated Products Inc.',
            'SWKS.V': 'Skyworks Solutions Inc.',
            'QRVO.V': 'Qorvo Inc.',
            'MPWR.V': 'Monolithic Power Systems Inc.',
            'SLAB.V': 'Silicon Laboratories Inc.',
            'CRUS.V': 'Cirrus Logic Inc.',
            'RMBS.V': 'Rambus Inc.',
            'MRVL.V': 'Marvell Technology Inc.',
            'XLNX.V': 'Xilinx Inc.',
            'ALTR.V': 'Altair Engineering Inc.',
            'CDNS.V': 'Cadence Design Systems Inc.',
            'SNPS.V': 'Synopsys Inc.',
            'ANSS.V': 'ANSYS Inc.',
            'ADSK.V': 'Autodesk Inc.',
            'PTC.V': 'PTC Inc.',
            'WORK.V': 'Slack Technologies Inc.',
            'FIVN.V': 'Five9 Inc.',
            'RING.V': 'Ring Inc.',
            'TWLO.V': 'Twilio Inc.',
            'BAND.V': 'Bandwidth Inc.',
            'SMAR.V': 'Smartsheet Inc.',
            'PLAN.V': 'Anaplan Inc.',
            'PCTY.V': 'Paylocity Holding Corporation',
            'PAYC.V': 'Paycom Software Inc.',
            'COUP.V': 'Coupa Software Incorporated',
            'BILL.V': 'Bill.com Holdings Inc.',
            'AFRM.V': 'Affirm Holdings Inc.',
            'UPST.V': 'Upstart Holdings Inc.',
            'OPEN.V': 'Opendoor Technologies Inc.',
            'RDFN.V': 'Redfin Corporation',
            'Z.V': 'Zillow Group Inc.',
            'EXPI.V': 'eXp World Holdings Inc.',
            'COMP.V': 'Compass Inc.',
            'RMAX.V': 'RE/MAX Holdings Inc.',
            'HOUS.V': 'Anywhere Real Estate Inc.',
            'RESI.V': 'Front Yard Residential Corporation',
            'AMC.V': 'AMC Entertainment Holdings Inc.',
            'NKLA.V': 'Nikola Corporation',
            'WKHS.V': 'Workhorse Group Inc.',
            'RIDE.V': 'Lordstown Motors Corp.',
            'GOEV.V': 'Canoo Inc.',
            'HYLN.V': 'Hyliion Holdings Corp.',
            'BLNK.V': 'Blink Charging Co.',
            'CHPT.V': 'ChargePoint Holdings Inc.',
            'EVGO.V': 'EVgo Inc.',
            'VLTA.V': 'Volta Inc.',
            'SBE.V': 'Solid Power Inc.',
            'QS.V': 'QuantumScape Corporation',
            'STEM.V': 'Stem Inc.',
            'ENPH.V': 'Enphase Energy Inc.',
            'SEDG.V': 'SolarEdge Technologies Inc.',
            'SPWR.V': 'SunPower Corporation',
            'FSLR.V': 'First Solar Inc.',
            'RUN.V': 'Sunrun Inc.',
            'NOVA.V': 'Sunnova Energy International Inc.',
            'CSIQ.V': 'Canadian Solar Inc.',
            'JKS.V': 'JinkoSolar Holding Co. Ltd.',
            'DQ.V': 'Daqo New Energy Corp.',
            'SOL.V': 'Emeren Group Ltd.',
            'MAXN.V': 'Maxeon Solar Technologies Ltd.',
            'ARRY.V': 'Array Technologies Inc.',
            'BEPC.V': 'Brookfield Renewable Corporation',
            'NEE.V': 'NextEra Energy Inc.',
            'AEP.V': 'American Electric Power Company Inc.',
            'SO.V': 'Southern Company',
            'D.V': 'Dominion Energy Inc.',
            'DUK.V': 'Duke Energy Corporation',
            'EXC.V': 'Exelon Corporation',
            'XEL.V': 'Xcel Energy Inc.',
            'WEC.V': 'WEC Energy Group Inc.',
            'ED.V': 'Consolidated Edison Inc.',
            'EIX.V': 'Edison International',
            'SRE.V': 'Sempra Energy',
            'PEG.V': 'Public Service Enterprise Group Incorporated',
            'PCG.V': 'PG&E Corporation',
            'AWK.V': 'American Water Works Company Inc.',
            'ATO.V': 'Atmos Energy Corporation',
            'CMS.V': 'CMS Energy Corporation',
            'DTE.V': 'DTE Energy Company',
            'NI.V': 'NiSource Inc.',
            'LNT.V': 'Alliant Energy Corporation',
            'EVRG.V': 'Evergy Inc.',
            'ES.V': 'Eversource Energy',
            'FE.V': 'FirstEnergy Corp.',
            'CNP.V': 'CenterPoint Energy Inc.',
            'ETR.V': 'Entergy Corporation',
            'AES.V': 'AES Corporation',
            'PPL.V': 'PPL Corporation',
            'PNW.V': 'Pinnacle West Capital Corporation',
            'UGI.V': 'UGI Corporation',
            'SWX.V': 'Southwest Gas Holdings Inc.',
            'OGE.V': 'OGE Energy Corp.',
            'MDU.V': 'MDU Resources Group Inc.',
            'BKH.V': 'Black Hills Corporation',
            'AVA.V': 'Avista Corporation',
            'POR.V': 'Portland General Electric Company',
            'IDA.V': 'IDACORP Inc.',
            'NWE.V': 'NorthWestern Corporation',
            'OTTR.V': 'Otter Tail Corporation',
            'ALE.V': 'Allete Inc.',
            'HE.V': 'Hawaiian Electric Industries Inc.',
            'UTL.V': 'Unitil Corporation',
            'MGEE.V': 'MGE Energy Inc.',
            'WR.V': 'Weir Group PLC',
            'SPXC.V': 'SPX Technologies Inc.',
            'FLS.V': 'Flowserve Corporation',
            'PH.V': 'Parker-Hannifin Corporation',
            'ETN.V': 'Eaton Corporation plc',
            'EMR.V': 'Emerson Electric Co.',
            'ROK.V': 'Rockwell Automation Inc.',
            'HON.V': 'Honeywell International Inc.',
            'ITW.V': 'Illinois Tool Works Inc.',
            'TXT.V': 'Textron Inc.',
            'RTX.V': 'Raytheon Technologies Corporation',
            'LMT.V': 'Lockheed Martin Corporation',
            'NOC.V': 'Northrop Grumman Corporation',
            'GD.V': 'General Dynamics Corporation',
            'BA.V': 'Boeing Company',
            'HII.V': 'Huntington Ingalls Industries Inc.',
            'LHX.V': 'L3Harris Technologies Inc.',
            'TDG.V': 'TransDigm Group Incorporated',
            'CW.V': 'Curtiss-Wright Corporation',
            'KTOS.V': 'Kratos Defense & Security Solutions Inc.',
            'AVAV.V': 'AeroVironment Inc.',
            'AJRD.V': 'Aerojet Rocketdyne Holdings Inc.',
            'MRCY.V': 'Mercury Systems Inc.',
            'VSAT.V': 'Viasat Inc.',
            'GILT.V': 'Gilat Satellite Networks Ltd.',
            'IRDM.V': 'Iridium Communications Inc.',
            'GSAT.V': 'Globalstar Inc.',
            'ORBC.V': 'Orbcomm Inc.',
            'MAXR.V': 'Maxar Technologies Inc.',
            'SPCE.V': 'Virgin Galactic Holdings Inc.',
            'RKLB.V': 'Rocket Lab USA Inc.',
            'ASTR.V': 'Astra Space Inc.',
            'VACQ.V': 'Vector Acquisition Corporation',
            'BKSY.V': 'BlackSky Technology Inc.',
            'PLNT.V': 'Planet Labs PBC',
            'SPIR.V': 'Spire Global Inc.',
            'ASTS.V': 'AST SpaceMobile Inc.',
            'MNTS.V': 'Momentus Inc.',
            'SRAC.V': 'Stable Road Acquisition Corp.',
            'NGCA.V': 'NextGen Acquisition Corporation',
            'IMPX.V': 'AEA-Bridges Impact Corp.',
            'TPGY.V': 'TPG Pace Beneficial Finance Corp.',
            'FGNA.V': 'FG New America Acquisition Corp.',
            'DFNS.V': 'Gores Metropoulos II Inc.',
            'GXGX.V': 'GX Acquisition Corp. II',
            'HCCO.V': 'HCM Acquisition Corp.',
            'TWND.V': 'Tailwind Acquisition Corp.',
            'ACTC.V': 'ArcLight Clean Transition Corp.',
            'PDAC.V': 'Peridot Acquisition Corp.',
            'ZNTE.V': 'Zanite Acquisition Corp.',
            'CLOV.V': 'Clover Health Investments Corp.',
            'SOFI.V': 'SoFi Technologies Inc.',
            'PTRA.V': 'Proterra Inc.',
            'JOBY.V': 'Joby Aviation Inc.',
            'LILM.V': 'Lilium N.V.',
            'EVTL.V': 'Vertical Aerospace Ltd.',
            'ACHR.V': 'Archer Aviation Inc.',
            'BLDE.V': 'Blade Air Mobility Inc.',
            'ESPR.V': 'Esperion Therapeutics Inc.',
            'VRTX.V': 'Vertex Pharmaceuticals Incorporated',
            'BIIB.V': 'Biogen Inc.',
            'REGN.V': 'Regeneron Pharmaceuticals Inc.',
            'AMGN.V': 'Amgen Inc.',
            'BMRN.V': 'BioMarin Pharmaceutical Inc.',
            'ILMN.V': 'Illumina Inc.',
            'INCY.V': 'Incyte Corporation',
            'ACAD.V': 'ACADIA Pharmaceuticals Inc.',
            'HALO.V': 'Halozyme Therapeutics Inc.',
            'EXEL.V': 'Exelixis Inc.',
            'FOLD.V': 'Amicus Therapeutics Inc.',
            'IONS.V': 'Ionis Pharmaceuticals Inc.',
            'SAGE.V': 'Sage Therapeutics Inc.',
            'RARE.V': 'Ultragenyx Pharmaceutical Inc.',
            'BLUE.V': 'bluebird bio Inc.',
            'CRSP.V': 'CRISPR Therapeutics AG',
            'EDIT.V': 'Editas Medicine Inc.',
            'NTLA.V': 'Intellia Therapeutics Inc.',
            'BEAM.V': 'Beam Therapeutics Inc.',
            'PRIME.V': 'Prime Medicine Inc.',
            'VERV.V': 'Verve Therapeutics Inc.',
            'MASS.V': 'Massimo Squalantotinib Inc.',
            'ALNY.V': 'Alnylam Pharmaceuticals Inc.',
            'ARWR.V': 'Arrowhead Pharmaceuticals Inc.',
            'DRNA.V': 'Dicerna Pharmaceuticals Inc.',
            'MORF.V': 'Morphic Holding Inc.',
            'TGTX.V': 'TG Therapeutics Inc.',
            'ADPT.V': 'Adaptive Biotechnologies Corporation',
            'FATE.V': 'Fate Therapeutics Inc.',
            'KITE.V': 'Kite Pharma Inc.',
            'JUNO.V': 'Juno Therapeutics Inc.',
            'CELG.V': 'Celgene Corporation',
            'NKTR.V': 'Nektar Therapeutics',
            'BPMC.V': 'Blueprint Medicines Corporation',
            'PTCT.V': 'PTC Therapeutics Inc.',
            'SGEN.V': 'Seagen Inc.',
            'IMMU.V': 'Immunomedics Inc.',
            'AXSM.V': 'Axsome Therapeutics Inc.',
            'CRBP.V': 'Corbus Pharmaceuticals Holdings Inc.',
            'CBPO.V': 'Canopy Growth Corporation',
            'WEED.V': 'Canopy Growth Corporation',
            'APHA.V': 'Aphria Inc.',
            'CRON.V': 'Cronos Group Inc.',
            'TLRY.V': 'Tilray Inc.',
            'CGC.V': 'Canopy Growth Corporation',
            'HEXO.V': 'HEXO Corp.',
            'OGI.V': 'OrganiGram Holdings Inc.',
            'LABS.V': 'MediPharm Labs Corp.',
            'VIDA.V': 'Vida Cannabis Corp.',
            'TGOD.V': 'The Green Organic Dutchman Holdings Ltd.',
            'ZENA.V': 'Zenabis Global Inc.',
            'CLIQ.V': 'Cliq Digital AG',
            'NUMI.V': 'Numinus Wellness Inc.',
            'MMED.V': 'Mind Medicine (MindMed) Inc.',
            'CYBN.V': 'Cybin Inc.',
            'FTRP.V': 'Field Trip Health Ltd.',
            'SHRM.V': 'Champignon Brands Inc.',
            'BUZZ.V': 'BuzzFeed Inc.',
            'GDNP.V': 'GreenSpace Brands Inc.',
            'BEER.V': 'Benchmark Brewing Company',
            'NTAR.V': 'Nextech AR Solutions Corp.',
            'NETE.V': 'Network Media Group Inc.',
            'DGTL.V': 'Digital Brands Group Corp.',
            'HIRE.V': 'Hire Technologies Inc.',
            'NRTH.V': 'Northern Graphite Corporation',
            'FLUX.V': 'Flux Power Holdings Inc.',
            'SOLR.V': 'Solarvest BioEnergy Inc.',
            'GRVI.V': 'Grove Inc.',
            'GAIA.V': 'Gaia Grow Corp.',
            'SOIL.V': 'Soil Connect Inc.',
            'TECH.V': 'Technosign Inc.',
            'LAKE.V': 'Lake Resources N.L.',
            'ROCK.V': 'Rock Tech Lithium Inc.',
            'FTCO.V': 'Fortune Bay Corp.',
            'GOLD.V': 'Gold Reserve Inc.',
            'SILV.V': 'SilverCrest Metals Inc.',
            'ZINC.V': 'Zinc8 Energy Solutions Inc.',
            'LION.V': 'Lion One Metals Limited',
            'GPRO.V': 'GoPro Inc.',
            'GDXJ.V': 'VanEck Vectors Junior Gold Miners ETF',
            'RECO.V': 'Reconnaissance Energy Africa Ltd.',
            'CSTR.V': 'CanStrip Resources Corp.',
            'MOGO.V': 'Mogo Inc.',
            'BIGG.V': 'BIGG Digital Assets Inc.',
            'HIVE.V': 'HIVE Blockchain Technologies Ltd.',
            'BITF.V': 'Bitfarms Ltd.',
            'DMGI.V': 'DMG Blockchain Solutions Inc.',
            'FORT.V': 'Fortress Technologies Inc.',
            'COIN.V': 'Coinbase Global Inc.',
            'GLXY.V': 'Galaxy Digital Holdings Ltd.',
            'BTCC.V': 'Purpose Bitcoin ETF',
            'ETHX.V': 'CI Galaxy Ethereum ETF',
            'BTCX.V': 'CI Galaxy Bitcoin ETF',
            'EBIT.V': 'Evolve Bitcoin ETF',
            'BTCY.V': 'Fidelity Advantage Bitcoin ETF',
            'QBTC.V': 'Purpose Bitcoin ETF',
            'ETHQ.V': 'Purpose Ether ETF',
            'BTCQ.V': 'Purpose Bitcoin ETF',
            'MSTR.V': 'MicroStrategy Incorporated',
            'RIOT.V': 'Riot Blockchain Inc.',
            'MARA.V': 'Marathon Digital Holdings Inc.',
            'CLSK.V': 'CleanSpark Inc.',
            'BTBT.V': 'Bit Digital Inc.',
            'EBON.V': 'Ebang International Holdings Inc.',
            'CAN.V': 'Canaan Inc.',
            'BTCM.V': 'BTC Digital Ltd.',
            'WULF.V': 'TeraWulf Inc.',
            'GREE.V': 'Greenidge Generation Holdings Inc.',
            'CIFR.V': 'Cipher Mining Inc.',
            'BFRI.V': 'Bitfufu Inc.',
            'CORZ.V': 'Core Scientific Inc.',
            'APLD.V': 'Applied Digital Corporation',
            'ARBK.V': 'Argo Blockchain PLC',
            'HUTMF.V': 'Hut 8 Mining Corp.',
            'BITK.V': 'Bitfarms Ltd.',
            'CCTL.V': 'CatalystOne Solutions ASA',
            'MIGI.V': 'Mogo Inc.',
            'VERY.V': 'Vicinity Motor Corp.',
            'DGHI.V': 'Digihost Technology Inc.',
            'INTV.V': 'Integral Technologies Inc.',
            'NVEI.V': 'Nuvei Corporation',
            'LSPD.V': 'Lightspeed POS Inc.',
            'REAL.V': 'Real Matters Inc.',
            'DOCN.V': 'DigitalOcean Holdings Inc.',
            'DOCU.V': 'DocuSign Inc.',
            'ZM.V': 'Zoom Video Communications Inc.',
            'TEAM.V': 'Atlassian Corporation Plc',
            'NOW.V': 'ServiceNow Inc.',
            'WDAY.V': 'Workday Inc.',
            'OKTA.V': 'Okta Inc.',
            'SNOW.V': 'Snowflake Inc.',
            'DDOG.V': 'Datadog Inc.',
            'ESTC.V': 'Elastic N.V.',
            'SPLK.V': 'Splunk Inc.',
            'CRWD.V': 'CrowdStrike Holdings Inc.',
            'ZS.V': 'Zscaler Inc.',
            'PANW.V': 'Palo Alto Networks Inc.',
            'FTNT.V': 'Fortinet Inc.',
            'CYBR.V': 'CyberArk Software Ltd.',
            'TENB.V': 'Tenable Holdings Inc.',
            'SAIL.V': 'SailPoint Technologies Holdings Inc.',
            'VRNS.V': 'Varonis Systems Inc.',
            'PFPT.V': 'Proofpoint Inc.',
            'FEYE.V': 'FireEye Inc.',
            'CHKP.V': 'Check Point Software Technologies Ltd.',
            'S.V': 'SentinelOne Inc.',
            'QLYS.V': 'Qualys Inc.',
            'RPRX.V': 'Rapid7 Inc.',
            'AVGO.V': 'Broadcom Inc.',
            'QCOM.V': 'QUALCOMM Incorporated',
            'TXN.V': 'Texas Instruments Incorporated',
            'AVGO.V': 'Broadcom Inc.',
            'LRCX.V': 'Lam Research Corporation',
            'AMAT.V': 'Applied Materials Inc.',
            'KLAC.V': 'KLA Corporation',
            'MCHP.V': 'Microchip Technology Incorporated',
            'MXIM.V': 'Maxim Integrated Products Inc.',
            'SWKS.V': 'Skyworks Solutions Inc.',
            'QRVO.V': 'Qorvo Inc.',
            'MPWR.V': 'Monolithic Power Systems Inc.',
            'SLAB.V': 'Silicon Laboratories Inc.',
            'CRUS.V': 'Cirrus Logic Inc.',
            'RMBS.V': 'Rambus Inc.',
            'MRVL.V': 'Marvell Technology Inc.',
            'XLNX.V': 'Xilinx Inc.',
            'ALTR.V': 'Altair Engineering Inc.',
            'CDNS.V': 'Cadence Design Systems Inc.',
            'SNPS.V': 'Synopsys Inc.',
            'ANSS.V': 'ANSYS Inc.',
            'ADSK.V': 'Autodesk Inc.',
            'PTC.V': 'PTC Inc.',
            'WORK.V': 'Slack Technologies Inc.',
            'FIVN.V': 'Five9 Inc.',
            'RING.V': 'Ring Inc.',
            'TWLO.V': 'Twilio Inc.',
            'BAND.V': 'Bandwidth Inc.',
            'SMAR.V': 'Smartsheet Inc.',
            'PLAN.V': 'Anaplan Inc.',
            'PCTY.V': 'Paylocity Holding Corporation',
            'PAYC.V': 'Paycom Software Inc.',
            'COUP.V': 'Coupa Software Incorporated',
            'BILL.V': 'Bill.com Holdings Inc.',
            'AFRM.V': 'Affirm Holdings Inc.',
            'UPST.V': 'Upstart Holdings Inc.',
            'OPEN.V': 'Opendoor Technologies Inc.',
            'RDFN.V': 'Redfin Corporation',
            'Z.V': 'Zillow Group Inc.',
            'EXPI.V': 'eXp World Holdings Inc.',
            'COMP.V': 'Compass Inc.',
            'RMAX.V': 'RE/MAX Holdings Inc.',
            'HOUS.V': 'Anywhere Real Estate Inc.',
            'RESI.V': 'Front Yard Residential Corporation',
            'AMC.V': 'AMC Entertainment Holdings Inc.',
            'NKLA.V': 'Nikola Corporation',
            'WKHS.V': 'Workhorse Group Inc.',
            'RIDE.V': 'Lordstown Motors Corp.',
            'GOEV.V': 'Canoo Inc.',
            'HYLN.V': 'Hyliion Holdings Corp.',
            'BLNK.V': 'Blink Charging Co.',
            'CHPT.V': 'ChargePoint Holdings Inc.',
            'EVGO.V': 'EVgo Inc.',
            'VLTA.V': 'Volta Inc.',
            'SBE.V': 'Solid Power Inc.',
            'QS.V': 'QuantumScape Corporation',
            'STEM.V': 'Stem Inc.',
            'ENPH.V': 'Enphase Energy Inc.',
            'SEDG.V': 'SolarEdge Technologies Inc.',
            'SPWR.V': 'SunPower Corporation',
            'FSLR.V': 'First Solar Inc.',
            'RUN.V': 'Sunrun Inc.',
            'NOVA.V': 'Sunnova Energy International Inc.',
            'CSIQ.V': 'Canadian Solar Inc.',
            'JKS.V': 'JinkoSolar Holding Co. Ltd.',
            'DQ.V': 'Daqo New Energy Corp.',
            'SOL.V': 'Emeren Group Ltd.',
            'MAXN.V': 'Maxeon Solar Technologies Ltd.',
            'ARRY.V': 'Array Technologies Inc.',
            'BEPC.V': 'Brookfield Renewable Corporation',
            'NEE.V': 'NextEra Energy Inc.',
            'AEP.V': 'American Electric Power Company Inc.',
            'SO.V': 'Southern Company',
            'D.V': 'Dominion Energy Inc.',
            'DUK.V': 'Duke Energy Corporation',
            'EXC.V': 'Exelon Corporation',
            'XEL.V': 'Xcel Energy Inc.',
            'WEC.V': 'WEC Energy Group Inc.',
            'ED.V': 'Consolidated Edison Inc.',
            'EIX.V': 'Edison International',
            'SRE.V': 'Sempra Energy',
            'PEG.V': 'Public Service Enterprise Group Incorporated',
            'PCG.V': 'PG&E Corporation',
            'AWK.V': 'American Water Works Company Inc.',
            'ATO.V': 'Atmos Energy Corporation',
            'CMS.V': 'CMS Energy Corporation',
            'DTE.V': 'DTE Energy Company',
            'NI.V': 'NiSource Inc.',
            'LNT.V': 'Alliant Energy Corporation',
            'EVRG.V': 'Evergy Inc.',
            'ES.V': 'Eversource Energy',
            'FE.V': 'FirstEnergy Corp.',
            'CNP.V': 'CenterPoint Energy Inc.',
            'ETR.V': 'Entergy Corporation',
            'AES.V': 'AES Corporation',
            'PPL.V': 'PPL Corporation',
            'PNW.V': 'Pinnacle West Capital Corporation',
            'UGI.V': 'UGI Corporation',
            'SWX.V': 'Southwest Gas Holdings Inc.',
            'OGE.V': 'OGE Energy Corp.',
            'MDU.V': 'MDU Resources Group Inc.',
            'BKH.V': 'Black Hills Corporation',
            'AVA.V': 'Avista Corporation',
            'POR.V': 'Portland General Electric Company',
            'IDA.V': 'IDACORP Inc.',
            'NWE.V': 'NorthWestern Corporation',
            'OTTR.V': 'Otter Tail Corporation',
            'ALE.V': 'Allete Inc.',
            'HE.V': 'Hawaiian Electric Industries Inc.',
            'UTL.V': 'Unitil Corporation',
            'MGEE.V': 'MGE Energy Inc.',
            'WR.V': 'Weir Group PLC',
            'SPXC.V': 'SPX Technologies Inc.',
            'FLS.V': 'Flowserve Corporation',
            'PH.V': 'Parker-Hannifin Corporation',
            'ETN.V': 'Eaton Corporation plc',
            'EMR.V': 'Emerson Electric Co.',
            'ROK.V': 'Rockwell Automation Inc.',
            'HON.V': 'Honeywell International Inc.',
            'ITW.V': 'Illinois Tool Works Inc.',
            'TXT.V': 'Textron Inc.',
            'RTX.V': 'Raytheon Technologies Corporation',
            'LMT.V': 'Lockheed Martin Corporation',
            'NOC.V': 'Northrop Grumman Corporation',
            'GD.V': 'General Dynamics Corporation',
            'BA.V': 'Boeing Company',
            'HII.V': 'Huntington Ingalls Industries Inc.',
            'LHX.V': 'L3Harris Technologies Inc.',
            'TDG.V': 'TransDigm Group Incorporated',
            'CW.V': 'Curtiss-Wright Corporation',
            'KTOS.V': 'Kratos Defense & Security Solutions Inc.',
            'AVAV.V': 'AeroVironment Inc.',
            'AJRD.V': 'Aerojet Rocketdyne Holdings Inc.',
            'MRCY.V': 'Mercury Systems Inc.',
            'VSAT.V': 'Viasat Inc.',
            'GILT.V': 'Gilat Satellite Networks Ltd.',
            'IRDM.V': 'Iridium Communications Inc.',
            'GSAT.V': 'Globalstar Inc.',
            'ORBC.V': 'Orbcomm Inc.',
            'MAXR.V': 'Maxar Technologies Inc.',
            'SPCE.V': 'Virgin Galactic Holdings Inc.',
            'RKLB.V': 'Rocket Lab USA Inc.',
            'ASTR.V': 'Astra Space Inc.',
            'VACQ.V': 'Vector Acquisition Corporation',
            'BKSY.V': 'BlackSky Technology Inc.',
            'PLNT.V': 'Planet Labs PBC',
            'SPIR.V': 'Spire Global Inc.',
            'ASTS.V': 'AST SpaceMobile Inc.',
            'MNTS.V': 'Momentus Inc.',
            'SRAC.V': 'Stable Road Acquisition Corp.',
            'NGCA.V': 'NextGen Acquisition Corporation',
            'IMPX.V': 'AEA-Bridges Impact Corp.',
            'TPGY.V': 'TPG Pace Beneficial Finance Corp.',
            'FGNA.V': 'FG New America Acquisition Corp.',
            'DFNS.V': 'Gores Metropoulos II Inc.',
            'GXGX.V': 'GX Acquisition Corp. II',
            'HCCO.V': 'HCM Acquisition Corp.',
            'TWND.V': 'Tailwind Acquisition Corp.',
            'ACTC.V': 'ArcLight Clean Transition Corp.',
            'PDAC.V': 'Peridot Acquisition Corp.',
            'ZNTE.V': 'Zanite Acquisition Corp.',
            'CLOV.V': 'Clover Health Investments Corp.',
            'SOFI.V': 'SoFi Technologies Inc.',
            'PTRA.V': 'Proterra Inc.',
            'JOBY.V': 'Joby Aviation Inc.',
            'LILM.V': 'Lilium N.V.',
            'EVTL.V': 'Vertical Aerospace Ltd.',
            'ACHR.V': 'Archer Aviation Inc.',
            'BLDE.V': 'Blade Air Mobility Inc.',
            'ESPR.V': 'Esperion Therapeutics Inc.',
            'VRTX.V': 'Vertex Pharmaceuticals Incorporated',
            'BIIB.V': 'Biogen Inc.',
            'REGN.V': 'Regeneron Pharmaceuticals Inc.',
            'AMGN.V': 'Amgen Inc.',
            'BMRN.V': 'BioMarin Pharmaceutical Inc.',
            'ILMN.V': 'Illumina Inc.',
            'INCY.V': 'Incyte Corporation',
            'ACAD.V': 'ACADIA Pharmaceuticals Inc.',
            'HALO.V': 'Halozyme Therapeutics Inc.',
            'EXEL.V': 'Exelixis Inc.',
            'FOLD.V': 'Amicus Therapeutics Inc.',
            'IONS.V': 'Ionis Pharmaceuticals Inc.',
            'SAGE.V': 'Sage Therapeutics Inc.',
            'RARE.V': 'Ultragenyx Pharmaceutical Inc.',
            'BLUE.V': 'bluebird bio Inc.',
            'CRSP.V': 'CRISPR Therapeutics AG',
            'EDIT.V': 'Editas Medicine Inc.',
            'NTLA.V': 'Intellia Therapeutics Inc.',
            'BEAM.V': 'Beam Therapeutics Inc.',
            'PRIME.V': 'Prime Medicine Inc.',
            'VERV.V': 'Verve Therapeutics Inc.',
            'MASS.V': 'Massimo Squalantotinib Inc.',
            'ALNY.V': 'Alnylam Pharmaceuticals Inc.',
            'ARWR.V': 'Arrowhead Pharmaceuticals Inc.',
            'DRNA.V': 'Dicerna Pharmaceuticals Inc.',
            'MORF.V': 'Morphic Holding Inc.',
            'TGTX.V': 'TG Therapeutics Inc.',
            'ADPT.V': 'Adaptive Biotechnologies Corporation',
            'FATE.V': 'Fate Therapeutics Inc.',
            'KITE.V': 'Kite Pharma Inc.',
            'JUNO.V': 'Juno Therapeutics Inc.',
            'CELG.V': 'Celgene Corporation',
            'NKTR.V': 'Nektar Therapeutics',
            'BPMC.V': 'Blueprint Medicines Corporation',
            'PTCT.V': 'PTC Therapeutics Inc.',
            'SGEN.V': 'Seagen Inc.',
            'IMMU.V': 'Immunomedics Inc.',
            'AXSM.V': 'Axsome Therapeutics Inc.',
            'CRBP.V': 'Corbus Pharmaceuticals Holdings Inc.',
            'CBPO.V': 'Canopy Growth Corporation',
            'WEED.V': 'Canopy Growth Corporation',
            'APHA.V': 'Aphria Inc.',
            'CRON.V': 'Cronos Group Inc.',
            'TLRY.V': 'Tilray Inc.',
            'CGC.V': 'Canopy Growth Corporation',
            'HEXO.V': 'HEXO Corp.',
            'OGI.V': 'OrganiGram Holdings Inc.',
            'LABS.V': 'MediPharm Labs Corp.',
            'VIDA.V': 'Vida Cannabis Corp.',
            'TGOD.V': 'The Green Organic Dutchman Holdings Ltd.',
            'ZENA.V': 'Zenabis Global Inc.',
            'CLIQ.V': 'Cliq Digital AG',
            'NUMI.V': 'Numinus Wellness Inc.',
            'MMED.V': 'Mind Medicine (MindMed) Inc.',
            'CYBN.V': 'Cybin Inc.',
            'FTRP.V': 'Field Trip Health Ltd.',
            'SHRM.V': 'Champignon Brands Inc.',
            'BUZZ.V': 'BuzzFeed Inc.',
            'GDNP.V': 'GreenSpace Brands Inc.',
            'BEER.V': 'Benchmark Brewing Company',
            'NTAR.V': 'Nextech AR Solutions Corp.',
            'NETE.V': 'Network Media Group Inc.',
            'DGTL.V': 'Digital Brands Group Corp.',
            'HIRE.V': 'Hire Technologies Inc.',
            'NRTH.V': 'Northern Graphite Corporation',
            'FLUX.V': 'Flux Power Holdings Inc.',
            'SOLR.V': 'Solarvest BioEnergy Inc.',
            'GRVI.V': 'Grove Inc.',
            'GAIA.V': 'Gaia Grow Corp.',
            'SOIL.V': 'Soil Connect Inc.',
            'TECH.V': 'Technosign Inc.',
            'LAKE.V': 'Lake Resources N.L.',
            'ROCK.V': 'Rock Tech Lithium Inc.',
            'FTCO.V': 'Fortune Bay Corp.',
            'GOLD.V': 'Gold Reserve Inc.',
            'SILV.V': 'SilverCrest Metals Inc.',
            'ZINC.V': 'Zinc8 Energy Solutions Inc.',
            'LION.V': 'Lion One Metals Limited',
            'GPRO.V': 'GoPro Inc.',
            'GDXJ.V': 'VanEck Vectors Junior Gold Miners ETF',
            'RECO.V': 'Reconnaissance Energy Africa Ltd.',
            'CSTR.V': 'CanStrip Resources Corp.',
            'MOGO.V': 'Mogo Inc.',
            'BIGG.V': 'BIGG Digital Assets Inc.',
            'HIVE.V': 'HIVE Blockchain Technologies Ltd.',
            'BITF.V': 'Bitfarms Ltd.',
            'DMGI.V': 'DMG Blockchain Solutions Inc.',
            'FORT.V': 'Fortress Technologies Inc.',
            'COIN.V': 'Coinbase Global Inc.',
            'GLXY.V': 'Galaxy Digital Holdings Ltd.',
            'BTCC.V': 'Purpose Bitcoin ETF',
            'ETHX.V': 'CI Galaxy Ethereum ETF',
            'BTCX.V': 'CI Galaxy Bitcoin ETF',
            'EBIT.V': 'Evolve Bitcoin ETF',
            'BTCY.V': 'Fidelity Advantage Bitcoin ETF',
            'QBTC.V': 'Purpose Bitcoin ETF',
            'ETHQ.V': 'Purpose Ether ETF',
            'BTCQ.V': 'Purpose Bitcoin ETF',
            'MSTR.V': 'MicroStrategy Incorporated',
            'RIOT.V': 'Riot Blockchain Inc.',
            'MARA.V': 'Marathon Digital Holdings Inc.',
            'CLSK.V': 'CleanSpark Inc.',
            'BTBT.V': 'Bit Digital Inc.',
            'EBON.V': 'Ebang International Holdings Inc.',
            'CAN.V': 'Canaan Inc.',
            'BTCM.V': 'BTC Digital Ltd.',
            'WULF.V': 'TeraWulf Inc.',
            'GREE.V': 'Greenidge Generation Holdings Inc.',
            'CIFR.V': 'Cipher Mining Inc.',
            'BFRI.V': 'Bitfufu Inc.',
            'CORZ.V': 'Core Scientific Inc.',
            'APLD.V': 'Applied Digital Corporation',
            'ARBK.V': 'Argo Blockchain PLC',
            'HUTMF.V': 'Hut 8 Mining Corp.',
            'BITK.V': 'Bitfarms Ltd.',
            'CCTL.V': 'CatalystOne Solutions ASA',
            'MIGI.V': 'Mogo Inc.',
            'VERY.V': 'Vicinity Motor Corp.',
            'DGHI.V': 'Digihost Technology Inc.',
            'INTV.V': 'Integral Technologies Inc.',
            'NVEI.V': 'Nuvei Corporation',
            'LSPD.V': 'Lightspeed POS Inc.',
            'REAL.V': 'Real Matters Inc.',
            'DOCN.V': 'DigitalOcean Holdings Inc.',
            'DOCU.V': 'DocuSign Inc.',
            'ZM.V': 'Zoom Video Communications Inc.',
            'TEAM.V': 'Atlassian Corporation Plc',
            'NOW.V': 'ServiceNow Inc.',
            'WDAY.V': 'Workday Inc.',
            'OKTA.V': 'Okta Inc.',
            'SNOW.V': 'Snowflake Inc.',
            'DDOG.V': 'Datadog Inc.',
            'ESTC.V': 'Elastic N.V.',
            'SPLK.V': 'Splunk Inc.',
            'CRWD.V': 'CrowdStrike Holdings Inc.',
            'ZS.V': 'Zscaler Inc.',
            'PANW.V': 'Palo Alto Networks Inc.',
            'FTNT.V': 'Fortinet Inc.',
            'CYBR.V': 'CyberArk Software Ltd.',
            'TENB.V': 'Tenable Holdings Inc.',
            'SAIL.V': 'SailPoint Technologies Holdings Inc.',
            'VRNS.V': 'Varonis Systems Inc.',
            'PFPT.V': 'Proofpoint Inc.',
            'FEYE.V': 'FireEye Inc.',
            'CHKP.V': 'Check Point Software Technologies Ltd.',
            'S.V': 'SentinelOne Inc.',
            'QLYS.V': 'Qualys Inc.',
            'RPRX.V': 'Rapid7 Inc.',
            'AVGO.V': 'Broadcom Inc.',
            'QCOM.V': 'QUALCOMM Incorporated',
            'TXN.V': 'Texas Instruments Incorporated',
            'AVGO.V': 'Broadcom Inc.',
            'LRCX.V': 'Lam Research Corporation',
            'AMAT.V': 'Applied Materials Inc.',
            'KLAC.V': 'KLA Corporation',
            'MCHP.V': 'Microchip Technology Incorporated',
            'MXIM.V': 'Maxim Integrated Products Inc.',
            'SWKS.V': 'Skyworks Solutions Inc.',
            'QRVO.V': 'Qorvo Inc.',
            'MPWR.V': 'Monolithic Power Systems Inc.',
            'SLAB.V': 'Silicon Laboratories Inc.',
            'CRUS.V': 'Cirrus Logic Inc.',
            'RMBS.V': 'Rambus Inc.',
            'MRVL.V': 'Marvell Technology Inc.',
            'XLNX.V': 'Xilinx Inc.',
            'ALTR.V': 'Altair Engineering Inc.',
            'CDNS.V': 'Cadence Design Systems Inc.',
            'SNPS.V': 'Synopsys Inc.',
            'ANSS.V': 'ANSYS Inc.',
            'ADSK.V': 'Autodesk Inc.',
            'PTC.V': 'PTC Inc.',
            'WORK.V': 'Slack Technologies Inc.',
            'FIVN.V': 'Five9 Inc.',
            'RING.V': 'Ring Inc.',
            'TWLO.V': 'Twilio Inc.',
            'BAND.V': 'Bandwidth Inc.',
            'SMAR.V': 'Smartsheet Inc.',
            'PLAN.V': 'Anaplan Inc.',
            'PCTY.V': 'Paylocity Holding Corporation',
            'PAYC.V': 'Paycom Software Inc.',
            'COUP.V': 'Coupa Software Incorporated',
            'BILL.V': 'Bill.com Holdings Inc.',
            'AFRM.V': 'Affirm Holdings Inc.',
            'UPST.V': 'Upstart Holdings Inc.',
            'OPEN.V': 'Opendoor Technologies Inc.',
            'RDFN.V': 'Redfin Corporation',
            'Z.V': 'Zillow Group Inc.',
            'EXPI.V': 'eXp World Holdings Inc.',
            'COMP.V': 'Compass Inc.',
            'RMAX.V': 'RE/MAX Holdings Inc.',
            'HOUS.V': 'Anywhere Real Estate Inc.',
            'RESI.V': 'Front Yard Residential Corporation',
            'AMC.V': 'AMC Entertainment Holdings Inc.',
            'NKLA.V': 'Nikola Corporation',
            'WKHS.V': 'Workhorse Group Inc.',
            'RIDE.V': 'Lordstown Motors Corp.',
            'GOEV.V': 'Canoo Inc.',
            'HYLN.V': 'Hyliion Holdings Corp.',
            'BLNK.V': 'Blink Charging Co.',
            'CHPT.V': 'ChargePoint Holdings Inc.',
            'EVGO.V': 'EVgo Inc.',
            'VLTA.V': 'Volta Inc.',
            'SBE.V': 'Solid Power Inc.',
            'QS.V': 'QuantumScape Corporation',
            'STEM.V': 'Stem Inc.',
            'ENPH.V': 'Enphase Energy Inc.',
            'SEDG.V': 'SolarEdge Technologies Inc.',
            'SPWR.V': 'SunPower Corporation',
            'FSLR.V': 'First Solar Inc.',
            'RUN.V': 'Sunrun Inc.',
            'NOVA.V': 'Sunnova Energy International Inc.',
            'CSIQ.V': 'Canadian Solar Inc.',
            'JKS.V': 'JinkoSolar Holding Co. Ltd.',
            'DQ.V': 'Daqo New Energy Corp.',
            'SOL.V': 'Emeren Group Ltd.',
            'MAXN.V': 'Maxeon Solar Technologies Ltd.',
            'ARRY.V': 'Array Technologies Inc.',
            'BEPC.V': 'Brookfield Renewable Corporation',
            'NEE.V': 'NextEra Energy Inc.',
            'AEP.V': 'American Electric Power Company Inc.',
            'SO.V': 'Southern Company',
            'D.V': 'Dominion Energy Inc.',
            'DUK.V': 'Duke Energy Corporation',
            'EXC.V': 'Exelon Corporation',
            'XEL.V': 'Xcel Energy Inc.',
            'WEC.V': 'WEC Energy Group Inc.',
            'ED.V': 'Consolidated Edison Inc.',
            'EIX.V': 'Edison International',
            'SRE.V': 'Sempra Energy',
            'PEG.V': 'Public Service Enterprise Group Incorporated',
            'PCG.V': 'PG&E Corporation',
            'AWK.V': 'American Water Works Company Inc.',
            'ATO.V': 'Atmos Energy Corporation',
            'CMS.V': 'CMS Energy Corporation',
            'DTE.V': 'DTE Energy Company',
            'NI.V': 'NiSource Inc.',
            'LNT.V': 'Alliant Energy Corporation',
            'EVRG.V': 'Evergy Inc.',
            'ES.V': 'Eversource Energy',
            'FE.V': 'FirstEnergy Corp.',
            'CNP.V': 'CenterPoint Energy Inc.',
            'ETR.V': 'Entergy Corporation',
            'AES.V': 'AES Corporation',
            'PPL.V': 'PPL Corporation',
            'PNW.V': 'Pinnacle West Capital Corporation',
            'UGI.V': 'UGI Corporation',
            'SWX.V': 'Southwest Gas Holdings Inc.',
            'OGE.V': 'OGE Energy Corp.',
            'MDU.V': 'MDU Resources Group Inc.',
            'BKH.V': 'Black Hills Corporation',
            'AVA.V': 'Avista Corporation',
            'POR.V': 'Portland General Electric Company',
            'IDA.V': 'IDACORP Inc.',
            'NWE.V': 'NorthWestern Corporation',
            'OTTR.V': 'Otter Tail Corporation',
            'ALE.V': 'Allete Inc.',
            'HE.V': 'Hawaiian Electric Industries Inc.',
            'UTL.V': 'Unitil Corporation',
            'MGEE.V': 'MGE Energy Inc.',
            'WR.V': 'Weir Group PLC',
            'SPXC.V': 'SPX Technologies Inc.',
            'FLS.V': 'Flowserve Corporation',
            'PH.V': 'Parker-Hannifin Corporation',
            'ETN.V': 'Eaton Corporation plc',
            'EMR.V': 'Emerson Electric Co.',
            'ROK.V': 'Rockwell Automation Inc.',
            'HON.V': 'Honeywell International Inc.',
            'ITW.V': 'Illinois Tool Works Inc.',
            'TXT.V': 'Textron Inc.',
            'RTX.V': 'Raytheon Technologies Corporation',
            'LMT.V': 'Lockheed Martin Corporation',
            'NOC.V': 'Northrop Grumman Corporation',
            'GD.V': 'General Dynamics Corporation',
            'BA.V': 'Boeing Company',
            'HII.V': 'Huntington Ingalls Industries Inc.',
            'LHX.V': 'L3Harris Technologies Inc.',
            'TDG.V': 'TransDigm Group Incorporated',
            'CW.V': 'Curtiss-Wright Corporation',
            'KTOS.V': 'Kratos Defense & Security Solutions Inc.',
            'AVAV.V': 'AeroVironment Inc.',
            'AJRD.V': 'Aerojet Rocketdyne Holdings Inc.',
            'MRCY.V': 'Mercury Systems Inc.',
            'VSAT.V': 'Viasat Inc.',
            'GILT.V': 'Gilat Satellite Networks Ltd.',
            'IRDM.V': 'Iridium Communications Inc.',
            'GSAT.V': 'Globalstar Inc.',
            'ORBC.V': 'Orbcomm Inc.',
            'MAXR.V': 'Maxar Technologies Inc.',
            'SPCE.V': 'Virgin Galactic Holdings Inc.',
            'RKLB.V': 'Rocket Lab USA Inc.',
            'ASTR.V': 'Astra Space Inc.',
            'VACQ.V': 'Vector Acquisition Corporation',
            'BKSY.V': 'BlackSky Technology Inc.',
            'PLNT.V': 'Planet Labs PBC',
            'SPIR.V': 'Spire Global Inc.',
            'ASTS.V': 'AST SpaceMobile Inc.',
            'MNTS.V': 'Momentus Inc.',
            'SRAC.V': 'Stable Road Acquisition Corp.',
            'NGCA.V': 'NextGen Acquisition Corporation',
            'IMPX.V': 'AEA-Bridges Impact Corp.',
            'TPGY.V': 'TPG Pace Beneficial Finance Corp.',
            'FGNA.V': 'FG New America Acquisition Corp.',
            'DFNS.V': 'Gores Metropoulos II Inc.',
            'GXGX.V': 'GX Acquisition Corp. II',
            'HCCO.V': 'HCM Acquisition Corp.',
            'TWND.V': 'Tailwind Acquisition Corp.',
            'ACTC.V': 'ArcLight Clean Transition Corp.',
            'PDAC.V': 'Peridot Acquisition Corp.',
            'ZNTE.V': 'Zanite Acquisition Corp.',
            'CLOV.V': 'Clover Health Investments Corp.',
            'SOFI.V': 'SoFi Technologies Inc.',
            'PTRA.V': 'Proterra Inc.',
            'JOBY.V': 'Joby Aviation Inc.',
            'LILM.V': 'Lilium N.V.',
            'EVTL.V': 'Vertical Aerospace Ltd.',
            'ACHR.V': 'Archer Aviation Inc.',
            'BLDE.V': 'Blade Air Mobility Inc.',
            'ESPR.V': 'Esperion Therapeutics Inc.',
        }
        
        # Combine all stocks with Canadian preference
        self.all_stocks = {}
        
        # Add Canadian stocks first (TSX and TSX-V)
        self.all_stocks.update(self.canadian_stocks)
        self.all_stocks.update(self.tsx_v_stocks)
        
        # Add US stocks
        self.all_stocks.update(self.us_stocks)
        
        # Create list for easy searching
        self.stock_list = [(symbol, name) for symbol, name in self.all_stocks.items()]
        
        # Sort by putting Canadian stocks first, then US stocks
        self.stock_list.sort(key=lambda x: (
            0 if x[0].endswith('.TO') or x[0].endswith('.V') else 1,  # Canadian stocks first
            x[1]  # Then sort by company name
        ))
        
    def get_suggestions(self, query: str, max_results: int = 10) -> List[Dict[str, str]]:
        """Get stock suggestions based on query"""
        if not query or len(query) < 2:
            # Return top Canadian stocks if no query
            return [
                {'symbol': 'SHOP.TO', 'name': 'Shopify Inc.', 'exchange': 'TSX'},
                {'symbol': 'RY.TO', 'name': 'Royal Bank of Canada', 'exchange': 'TSX'},
                {'symbol': 'TD.TO', 'name': 'Toronto-Dominion Bank', 'exchange': 'TSX'},
                {'symbol': 'CNR.TO', 'name': 'Canadian National Railway', 'exchange': 'TSX'},
                {'symbol': 'BNS.TO', 'name': 'Bank of Nova Scotia', 'exchange': 'TSX'},
                {'symbol': 'AAPL', 'name': 'Apple Inc.', 'exchange': 'NASDAQ'},
                {'symbol': 'MSFT', 'name': 'Microsoft Corporation', 'exchange': 'NASDAQ'},
                {'symbol': 'GOOGL', 'name': 'Alphabet Inc.', 'exchange': 'NASDAQ'},
                {'symbol': 'AMZN', 'name': 'Amazon.com Inc.', 'exchange': 'NASDAQ'},
                {'symbol': 'TSLA', 'name': 'Tesla Inc.', 'exchange': 'NASDAQ'},
            ]
        
        query = query.upper()
        matches = []
        
        # Search for matches
        for symbol, name in self.stock_list:
            # Check if query matches symbol or company name
            if (query in symbol.upper() or 
                query in name.upper() or 
                name.upper().startswith(query) or
                symbol.upper().startswith(query)):
                
                # Determine exchange
                if symbol.endswith('.TO'):
                    exchange = 'TSX'
                elif symbol.endswith('.V'):
                    exchange = 'TSX-V'
                else:
                    exchange = 'US'
                
                matches.append({
                    'symbol': symbol,
                    'name': name,
                    'exchange': exchange
                })
                
                if len(matches) >= max_results:
                    break
        
        return matches
    
    def get_popular_canadian_stocks(self, limit: int = 20) -> List[Dict[str, str]]:
        """Get popular Canadian stocks"""
        popular = []
        canadian_symbols = [
            'SHOP.TO', 'RY.TO', 'TD.TO', 'CNR.TO', 'BNS.TO', 'BMO.TO', 'CNQ.TO',
            'CP.TO', 'SU.TO', 'ENB.TO', 'TRI.TO', 'WCN.TO', 'CSU.TO', 'ATD.TO',
            'MFC.TO', 'SLF.TO', 'CCL-B.TO', 'QSR.TO', 'DOL.TO', 'WFG.TO'
        ]
        
        for symbol in canadian_symbols[:limit]:
            if symbol in self.all_stocks:
                popular.append({
                    'symbol': symbol,
                    'name': self.all_stocks[symbol],
                    'exchange': 'TSX'
                })
        
        return popular
    
    def get_popular_us_stocks(self, limit: int = 20) -> List[Dict[str, str]]:
        """Get popular US stocks"""
        popular = []
        us_symbols = [
            'AAPL', 'MSFT', 'GOOGL', 'AMZN', 'TSLA', 'NVDA', 'META', 'NFLX',
            'AMD', 'INTC', 'PYPL', 'ADBE', 'CRM', 'ORCL', 'IBM', 'UBER',
            'SPOT', 'TWTR', 'SNAP', 'ZOOM'
        ]
        
        for symbol in us_symbols[:limit]:
            if symbol in self.all_stocks:
                popular.append({
                    'symbol': symbol,
                    'name': self.all_stocks[symbol],
                    'exchange': 'US'
                })
        
        return popular
    
    def format_suggestion(self, suggestion: Dict[str, str]) -> str:
        """Format suggestion for display"""
        return f"{suggestion['symbol']} - {suggestion['name']} ({suggestion['exchange']})"
    
    def is_valid_symbol(self, symbol: str) -> bool:
        """Check if symbol is in our database"""
        return symbol.upper() in self.all_stocks
    
    def get_company_name(self, symbol: str) -> Optional[str]:
        """Get company name for symbol"""
        return self.all_stocks.get(symbol.upper())
    
    def search_by_company_name(self, company_name: str, max_results: int = 5) -> List[Dict[str, str]]:
        """Search stocks by company name"""
        if not company_name or len(company_name) < 3:
            return []
        
        company_name = company_name.upper()
        matches = []
        
        for symbol, name in self.stock_list:
            if company_name in name.upper():
                # Determine exchange
                if symbol.endswith('.TO'):
                    exchange = 'TSX'
                elif symbol.endswith('.V'):
                    exchange = 'TSX-V'
                else:
                    exchange = 'US'
                
                matches.append({
                    'symbol': symbol,
                    'name': name,
                    'exchange': exchange
                })
                
                if len(matches) >= max_results:
                    break
        
        return matches
    
    def get_sector_stocks(self, sector: str, limit: int = 10) -> List[Dict[str, str]]:
        """Get stocks by sector (simplified categorization)"""
        sector_mapping = {
            'tech': ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'TSLA', 'NVDA', 'META', 'NFLX', 'SHOP.TO', 'LSPD.TO'],
            'finance': ['RY.TO', 'TD.TO', 'BNS.TO', 'BMO.TO', 'MFC.TO', 'SLF.TO', 'JPM', 'BAC', 'WFC'],
            'energy': ['CNQ.TO', 'SU.TO', 'ENB.TO', 'TRP.TO', 'XOM', 'CVX', 'COP'],
            'mining': ['ABX.TO', 'K.TO', 'AEM.TO', 'WPM.TO', 'FNV.TO', 'GLD', 'SLV'],
            'rail': ['CNR.TO', 'CP.TO', 'CNI.TO'],
            'retail': ['DOL.TO', 'ATD.TO', 'QSR.TO', 'WMT', 'TGT', 'COST'],
        }
        
        sector_symbols = sector_mapping.get(sector.lower(), [])
        results = []
        
        for symbol in sector_symbols[:limit]:
            if symbol in self.all_stocks:
                # Determine exchange
                if symbol.endswith('.TO'):
                    exchange = 'TSX'
                elif symbol.endswith('.V'):
                    exchange = 'TSX-V'
                else:
                    exchange = 'US'
                
                results.append({
                    'symbol': symbol,
                    'name': self.all_stocks[symbol],
                    'exchange': exchange
                })
        
        return results